### ISSUE TITLE
怎么自定义图片下载路径呢

### ISSUE THREAD

**Issue by candrwow** [xiaopansky/Sketch#27]

**Comment by xiaopansky** [comment]
没有简单的方法能够自定义下载路径，主要原因是下载路径的验证比较复杂，具体细节可参考源码中的LRUdiskcache，如果非要自定义的话就只能自定义一个完整的diskcache或者，具体可参考源码中的LRUdiskcache

**Comment by candrwow** [comment]
我这边根据sample修改了SaveImageAsyncTask下的路径，现在图片可以正常保存，您给我的建议中修改diskcache是否是因为修改SaveImageAsyncTask这个类存在较大隐患呢?

**Comment by candrwow** [comment]
作者，你好。我这边有个需求是单击后关闭图片界面，加入了onCLicklistener和longclick后，点击事件会和zoom操作冲突，虽然现在解决了这个问题，但是如果可以在库里本身增加onClick和longclick这两个常用的就好了。非常感谢

**Comment by candrwow** [comment]
缩放操作有时会出现这个闪退：

java.lang.IllegalArgumentException: pointerIndex out of range
                                                                    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                    at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                    at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                    at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:600)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                	at andr

-

**Comment by xiaopansky** [comment]
崩溃请看这篇文档 https://github.com/xiaopansky/Sketch/blob/master/docs/wiki/zoom.md

**Comment by xiaopansky** [comment]
另外关于图片下载路径的问题，你问的问题是如何修改图片下载路径，而SaveImageAsyncTask是用来将图片从默认的下载目录里保存到其它地方的，只是sample里的一个功能，同Sketch本身并没有关系

**Comment by candrwow** [comment]
你好，有的图片会出现点击进入查看图片，图片显示的是原图旋转90度的情况，这个问题要怎么处理呢

**Comment by xiaopansky** [comment]
Sketch本身并没有提供自动旋转图片的功能，有以下几种因素可能会造成这样的结果：
>* 你使用了旋转处理器RotateImageProcessor
>* 你的Activity开了自动旋转
>* 你的原图本身就是那样的
你先按照这几个因素逐一排查一下

**Comment by candrwow** [comment]
由于我对图片的相关知识掌握不多，我google了下资料，可能是因为图片信息里的旋转角度是90，如果是这种应该如何使用sketch去将图片角度正确显示呢

**Comment by xiaopansky** [comment]
这种情况目前Sketch没有方便的解决办法，但会是接下来版本的重点功能。现阶段你可以在图片显示完成后，通过ExifInterface读取图片的旋转角度，然后通过matrix旋转ImageView
