### ISSUE TITLE
MissingFormatArgumentException: Format specifier: 3A

### ISSUE THREAD

**Issue by xiaopansky** [xiaopansky/Sketch#28]
```java
java.util.MissingFormatArgumentException: Format specifier: 3A
	at java.util.Formatter.getArgument(Formatter.java:1111)
	at java.util.Formatter.doFormat(Formatter.java:1076)
	at java.util.Formatter.format(Formatter.java:1042)
	at java.util.Formatter.format(Formatter.java:1011)
	at java.lang.String.format(String.java:1999)
	at java.lang.String.format(String.java:1973)
	at me.xiaopan.sketch.SLog.w(SLog.java:228)
	at me.xiaopan.sketch.SLog.w(SLog.java:241)
	at me.xiaopan.sketch.util.DiskLruCache.deleteContents(DiskLruCache.java:259)
	at me.xiaopan.sketch.util.DiskLruCache.delete(DiskLruCache.java:776)
	at me.xiaopan.sketch.util.DiskLruCache.open$51f85bc7(DiskLruCache.java:326)
	at me.xiaopan.sketch.cache.LruDiskCache.installDiskCache(LruDiskCache.java:115)
	at me.xiaopan.sketch.cache.LruDiskCache.get(LruDiskCache.java:165)
	at me.xiaopan.sketch.request.DownloadRequest.runDispatch(DownloadRequest.java:129)
	at me.xiaopan.sketch.request.LoadRequest.runDispatch(LoadRequest.java:160)
	at me.xiaopan.sketch.request.AsyncRequest.executeDispatch(AsyncRequest.java:62)
	at me.xiaopan.sketch.request.AsyncRequest.run(AsyncRequest.java:19)
	at me.xiaopan.sketch.request.RequestExecutor$DispatchCallback.handleMessage(RequestExecutor.java:186)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```
发生版本：2.3.1
修复版本：将在下个版本2.3.2上修复

**Comment by deepu09** [comment]
How did u fix this issue? Can you please give some details?
